name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global --add safe.directory /github/workspace

      - name: Sync upstream repo
        run: |
          git clone git@github.com:0xfinn/nextjs-notion-starter-kit.git repo
          cd repo
          git remote add upstream git@github.com:transitive-bullshit/nextjs-notion-starter-kit.git
          git fetch upstream
          git merge upstream/main
          git push origin main
