name: Sync upstream repo

on:
  schedule:
    - cron: '0 0 * * *' # 每天同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Git sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:transitive-bullshit/nextjs-notion-starter-kit.git"
          source_branch: "main"
          destination_repo: "git@github.com:sylarxiong/nextjs-notion-starter-kit.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
